#!/usr/bin/env bash
# deploy/06_download_llm.sh — download LLM / Embedding / Reranker models
# Tries the official HuggingFace endpoint first, falls back to hf-mirror.com.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/common.sh"

[[ -f "${SCRIPT_DIR}/deploy.conf" ]] && source "${SCRIPT_DIR}/deploy.conf"
resolve_paths

log_step "Step 6 — Download LLM / Embedding / Reranker models"

LLM_MODEL_DIR="${BASE_DIR}/models/qwen3-14b"
EMBEDDING_MODEL_DIR="${BASE_DIR}/models/all-MiniLM-L6-v2"
RERANKER_MODEL_DIR="${BASE_DIR}/models/bge-reranker-base"
mkdir -p "${LLM_MODEL_DIR}" "${EMBEDDING_MODEL_DIR}" "${RERANKER_MODEL_DIR}"

export LLM_MODEL_DIR EMBEDDING_MODEL_DIR RERANKER_MODEL_DIR

init_conda

_hf_model_complete() {
    local local_dir="$1"
    [[ -f "${local_dir}/config.json" ]] || return 1
    ls "${local_dir}"/pytorch_model.bin \
       "${local_dir}"/model.safetensors \
       "${local_dir}"/*.safetensors 2>/dev/null | head -1 | grep -q .
}

_hf_download() {
    local repo_id="$1"
    local local_dir="$2"
    local label="${3:-${repo_id}}"

    if _hf_model_complete "${local_dir}"; then
        log_info "${label}: already downloaded at ${local_dir}, skipping."
        return 0
    fi

    log_info "Downloading: ${label}  (${repo_id})"
    log_info "  dest: ${local_dir}"

    _do_download() {
        local endpoint="$1"
        [[ -n "${endpoint}" ]] && log_info "  endpoint: ${endpoint}" \
                               || log_info "  endpoint: https://huggingface.co (official)"
        if conda_run "${AGENT_ENV}" hf --help >/dev/null 2>&1; then
            if [[ -n "${endpoint}" ]]; then
                HF_ENDPOINT="${endpoint}" HF_HUB_DISABLE_XET=1 \
                conda_run "${AGENT_ENV}" hf download \
                    "${repo_id}" \
                    --local-dir "${local_dir}"
            else
                HF_HUB_DISABLE_XET=1 \
                conda_run "${AGENT_ENV}" hf download \
                    "${repo_id}" \
                    --local-dir "${local_dir}"
            fi
        else
            if [[ -n "${endpoint}" ]]; then
                HF_ENDPOINT="${endpoint}" HF_HUB_DISABLE_XET=1 \
                conda_run "${AGENT_ENV}" python -m huggingface_hub download \
                    "${repo_id}" \
                    --local-dir "${local_dir}"
            else
                HF_HUB_DISABLE_XET=1 \
                conda_run "${AGENT_ENV}" python -m huggingface_hub download \
                    "${repo_id}" \
                    --local-dir "${local_dir}"
            fi
        fi
    }

    if _do_download "${HF_ENDPOINT:-}"; then
        log_success "${label} downloaded."
        return 0
    fi

    if [[ "${HF_ENDPOINT:-}" != "https://hf-mirror.com" ]]; then
        log_warn "${label}: official download failed, retrying with hf-mirror.com..."
        if _do_download "https://hf-mirror.com"; then
            log_success "${label} downloaded (via hf-mirror.com)."
            return 0
        fi
    fi

    log_error "${label} download failed on all sources."
    return 1
}

if [[ "${LLM_MODE:-local}" == "api" ]]; then
    log_info "LLM_MODE=api — skipping LLM download."

    if [[ -n "${API_KEY:-}" ]]; then
        _secrets="${PROJECT_ROOT}/api_keys.py"
        if [[ ! -f "${_secrets}" ]]; then
            log_info "Writing api_keys.py..."
            cat > "${_secrets}" <<EOF
# Auto-generated by deploy.sh — DO NOT COMMIT
LLM_API_KEY      = "${API_KEY}"
LLM_API_BASE_URL = "${API_BASE_URL:-https://api.deepseek.com/v1}"
LLM_API_MODEL    = "${API_MODEL:-deepseek-chat}"
LLM_API_MAX_TOKENS = 4096
EOF
            log_success "api_keys.py written."
        else
            log_info "api_keys.py already exists, skipping."
        fi
    else
        log_warn "API_KEY not set — api_keys.py not written."
    fi
else
    _hf_download "Qwen/Qwen3-14B" "${LLM_MODEL_DIR}" "Qwen3-14B (LLM)"
fi

_hf_download "sentence-transformers/all-MiniLM-L6-v2" \
             "${EMBEDDING_MODEL_DIR}" "all-MiniLM-L6-v2 (Embedding)" || true

_hf_download "BAAI/bge-reranker-base" \
             "${RERANKER_MODEL_DIR}" "bge-reranker-base (Reranker)" || true

echo ""
log_info "Model directories:"
for _d in "${LLM_MODEL_DIR}" "${EMBEDDING_MODEL_DIR}" "${RERANKER_MODEL_DIR}"; do
    if [[ -d "${_d}" ]]; then
        _sz=$(du -sh "${_d}" 2>/dev/null | cut -f1)
        if _hf_model_complete "${_d}"; then
            echo "  ${_d}  (${_sz}, complete)"
        else
            echo "  ${_d}  (${_sz}, incomplete)"
        fi
    else
        echo "  ${_d}  [NOT FOUND]"
    fi
done

log_done "Model download complete"
