#!/usr/bin/env bash
# deploy/08_patch_config.sh — patch config.yaml with deployed paths (preserves comments via ruamel.yaml)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/common.sh"

if [[ -z "${BASE_DIR:-}" ]]; then
    [[ -f "${SCRIPT_DIR}/deploy.conf" ]] && source "${SCRIPT_DIR}/deploy.conf"
    resolve_paths
fi

log_step "Step 8 — Patch config.yaml"

CONFIG_FILE="${PROJECT_ROOT}/config.yaml"
[[ -f "${CONFIG_FILE}" ]] || die "config.yaml not found at ${CONFIG_FILE}"

_backup="${CONFIG_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
cp "${CONFIG_FILE}" "${_backup}"
log_info "Backup: ${_backup}"

LLM_MODEL_DIR="${LLM_MODEL_DIR:-${BASE_DIR}/models/qwen3-14b}"
EMBEDDING_MODEL_DIR="${EMBEDDING_MODEL_DIR:-${BASE_DIR}/models/all-MiniLM-L6-v2}"
RERANKER_MODEL_DIR="${RERANKER_MODEL_DIR:-${BASE_DIR}/models/bge-reranker-base}"
_llm_model_name="${LLM_MODEL_NAME:-qwen3_14B}"
_llm_device="${LLM_DEVICE:-cuda:0}"
_nf_max_cpus_val="null"
[[ -n "${NF_MAX_CPUS:-}" ]] && _nf_max_cpus_val="${NF_MAX_CPUS}"

init_conda

# Install ruamel.yaml if not present (preserves YAML comments)
if ! conda_run "${AGENT_ENV}" python3 -c "import ruamel.yaml" 2>/dev/null; then
    conda_run "${AGENT_ENV}" pip install ruamel.yaml -q 2>/dev/null || true
fi

_has_ruamel=false
conda_run "${AGENT_ENV}" python3 -c "import ruamel.yaml" 2>/dev/null && _has_ruamel=true

if [[ "${_has_ruamel}" == "true" ]]; then
    log_info "Patching with ruamel.yaml (comments preserved)..."
    _yaml_lib="ruamel"
else
    log_warn "ruamel.yaml unavailable — falling back to PyYAML (comments will be stripped)"
    _yaml_lib="pyyaml"
fi

conda_run "${AGENT_ENV}" python3 - <<PYEOF
import sys

llm_mode         = "${LLM_MODE}"
base_dir         = "${BASE_DIR}"
sin_env          = "${SIN_ENV}"
model_name       = "${_llm_model_name}"
llm_device       = "${_llm_device}"
llm_dir          = "${LLM_MODEL_DIR}"
embed_dir        = "${EMBEDDING_MODEL_DIR}"
rerank_dir       = "${RERANKER_MODEL_DIR}"
sng_image_dir    = "${SINGULARITY_DIR}"
dorado_model_dir = "${DORADO_MODEL_DIR}"
pipeline_dir     = "${PIPELINE_DIR}/"
agent_data       = "${AGENT_DATA_DIR}"
server_port      = int("${SERVER_PORT}")
user_quota       = int("${USER_QUOTA_GB}")
sample_rate      = int("${DORADO_SAMPLE_RATE}")
nf_max_memory    = "${NF_MAX_MEMORY}"
nf_max_time      = "${NF_MAX_TIME}"
nf_max_cpus_s    = "${_nf_max_cpus_val}"
config_path      = "${CONFIG_FILE}"
yaml_lib         = "${_yaml_lib}"

def _set(d, key, val):
    old = d.get(key)
    if old != val:
        print(f"  {key}: {old!r} -> {val!r}")
        d[key] = val

if yaml_lib == "ruamel":
    from ruamel.yaml import YAML
    yaml = YAML(); yaml.preserve_quotes = True; yaml.width = 120
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.load(f)
    def save(cfg):
        with open(config_path, "w", encoding="utf-8") as f:
            yaml.dump(cfg, f)
else:
    import yaml as _yaml
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = _yaml.safe_load(f)
    def save(cfg):
        with open(config_path, "w", encoding="utf-8") as f:
            _yaml.dump(cfg, f, allow_unicode=True, default_flow_style=False,
                       sort_keys=False, width=120)

d = cfg.setdefault("data", {})
_set(d, "agent_data",            agent_data)
_set(d, "dorado_models",         dorado_model_dir)
_set(d, "singularity_image_dir", sng_image_dir)
_set(d, "pipeline_dir",          pipeline_dir)
_set(d, "dorado_sample_rate",    sample_rate)
_set(d, "user_quota_gb",         user_quota)

cfg.setdefault("tools", {}).setdefault("exec_env", {})
_set(cfg["tools"]["exec_env"], "type",     "conda")
_set(cfg["tools"]["exec_env"], "env_name", sin_env)

l = cfg.setdefault("llm", {})
mp = l.setdefault("model_paths", {})
if llm_mode == "local":
    _set(l, "model_name", model_name)
    _set(l, "device",     llm_device)
    _set(mp, model_name, llm_dir)
else:
    _set(l, "model_name", "openai_compatible")
_set(mp, "embedding", embed_dir)
_set(mp, "reranker",  rerank_dir)

w = cfg.setdefault("workflow", {})
_set(w, "max_memory", nf_max_memory)
_set(w, "max_time",   nf_max_time)
_set(w, "max_cpus",   None if nf_max_cpus_s == "null" else int(nf_max_cpus_s))

_set(cfg.setdefault("server", {}), "port", server_port)

save(cfg)
print("config.yaml patched.")
PYEOF

log_success "config.yaml updated."

# Write secrets.py for API mode
if [[ "${LLM_MODE}" == "api" && -n "${API_KEY:-}" ]]; then
    _secrets="${PROJECT_ROOT}/configs/secrets.py"
    if [[ ! -f "${_secrets}" ]]; then
        log_info "Writing configs/secrets.py..."
        cat > "${_secrets}" <<EOF
# Auto-generated by deploy.sh — DO NOT COMMIT
LLM_API_KEY      = "${API_KEY}"
LLM_API_BASE_URL = "${API_BASE_URL:-https://api.deepseek.com/v1}"
LLM_API_MODEL    = "${API_MODEL:-deepseek-chat}"
LLM_API_MAX_TOKENS = 4096
EOF
        log_success "configs/secrets.py written."
    fi
fi

log_done "Config patch complete"
